package com.propertytrader.core.board

object BoardFactory {

    fun classicBoard(): List<Space> = listOf(
        GoSpace(0),
        PropertySpace(1, "Ulica Wierzbowa", ColorGroup.A, price = 60, baseRent = 4),
        EventSpace(2, "Wydarzenie"),
        PropertySpace(3, "Ulica Klonowa", ColorGroup.A, price = 60, baseRent = 8),
        TaxSpace(4, "Podatek", amount = 200),
        TransitSpace(5, "Dworzec Polnocny", price = 200, rentByOwnedCount = listOf(25, 50, 100, 200)),
        PropertySpace(6, "Ulica Cedrowa", ColorGroup.B, price = 100, baseRent = 6),
        EventSpace(7, "Wydarzenie"),
        PropertySpace(8, "Ulica Bukowa", ColorGroup.B, price = 100, baseRent = 6),
        PropertySpace(9, "Ulica Debowa", ColorGroup.B, price = 120, baseRent = 8),
        JailSpace(10),
        PropertySpace(11, "Ulica Sosnowa", ColorGroup.C, price = 140, baseRent = 10),
        UtilitySpace(12, "Elektrownia Miejska", price = 150),
        PropertySpace(13, "Ulica Swierkowa", ColorGroup.C, price = 140, baseRent = 10),
        PropertySpace(14, "Ulica Jesionowa", ColorGroup.C, price = 160, baseRent = 12),
        TransitSpace(15, "Dworzec Wschodni", price = 200, rentByOwnedCount = listOf(25, 50, 100, 200)),
        PropertySpace(16, "Ulica Topolowa", ColorGroup.D, price = 180, baseRent = 14),
        EventSpace(17, "Wydarzenie"),
        PropertySpace(18, "Ulica Lipowa", ColorGroup.D, price = 180, baseRent = 14),
        PropertySpace(19, "Ulica Jaworowa", ColorGroup.D, price = 200, baseRent = 16),
        FreeParkingSpace(20),
        PropertySpace(21, "Ulica Kasztanowa", ColorGroup.E, price = 220, baseRent = 18),
        EventSpace(22, "Wydarzenie"),
        PropertySpace(23, "Ulica Grabowa", ColorGroup.E, price = 220, baseRent = 18),
        PropertySpace(24, "Ulica Brzozowa", ColorGroup.E, price = 240, baseRent = 20),
        TransitSpace(25, "Dworzec Poludniowy", price = 200, rentByOwnedCount = listOf(25, 50, 100, 200)),
        PropertySpace(26, "Ulica Akacjowa", ColorGroup.F, price = 260, baseRent = 22),
        PropertySpace(27, "Ulica Jarzebinowa", ColorGroup.F, price = 260, baseRent = 22),
        UtilitySpace(28, "Wodociagi Miejskie", price = 150),
        PropertySpace(29, "Ulica Platanowa", ColorGroup.F, price = 280, baseRent = 24),
        GoToJailSpace(30),
        PropertySpace(31, "Ulica Wiazowa", ColorGroup.G, price = 300, baseRent = 26),
        PropertySpace(32, "Ulica Modrzewiowa", ColorGroup.G, price = 300, baseRent = 26),
        EventSpace(33, "Wydarzenie"),
        PropertySpace(34, "Ulica Cyprysowa", ColorGroup.G, price = 320, baseRent = 28),
        TransitSpace(35, "Dworzec Zachodni", price = 200, rentByOwnedCount = listOf(25, 50, 100, 200)),
        EventSpace(36, "Wydarzenie"),
        PropertySpace(37, "Ulica Magnoliowa", ColorGroup.H, price = 350, baseRent = 35),
        TaxSpace(38, "Podatek luksusowy", amount = 100),
        PropertySpace(39, "Ulica Palisandrowa", ColorGroup.H, price = 400, baseRent = 50),
    )
}
